Chapter2課題
terry-man-com/furiPHP_exercise pull request #2
Opened 2021-12-22 00:11 UTC by terry-man-com

### カリキュラムURL

zhttps://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/02.md

### メッセージ
Chapter2の課題が終わりましたので確認お願いします🙇‍♀️

2021-12-22 00:33 UTC, kazu-taka requested changes
@terry-man-com 
コメントしたので修正お願いします✨

2021-12-22 00:33 UTC, kazu-taka commented on chap2_1.php
> +}
@terry-man-com 
公式のページifとelseif の後ろにはスペースを入れているので、同じようにスペースを入れるようにお願いします✨
https://www.php.net/manual/ja/control-structures.if.php

```php
if ($age < 20) {
    var_dump("あなたは未成年です。");
} elseif ($age == 20) {
    var_dump("成人式ですね、おめでとう！");
} else {
    var_dump("成人です。");
} 
```

VSCodeのフォーマッターを利用すると綺麗に修正できます！
右クリックメニュー(2本指でタップ)の「ドキュメントのフォーマット...」を指定
![image](https://user-images.githubusercontent.com/5278718/147014473-d64c86d7-b6ef-41d9-bf00-26a01a661132.png)

PHP Intelephenseを指定することで、フォーマッターを利用することが可能です😊
![image](https://user-images.githubusercontent.com/5278718/147014543-bbd1a4b4-1483-44fb-9940-1c6ca97eb59d.png)

2021-12-22 00:33 UTC, kazu-taka commented on chap2_2.php
> +}
@terry-man-com 
こちらもフォーマッターの利用をお願いします✨
`is_numeric($num)`で数値判定しているのはいいですね！
同じ条件を2回確認しているので、このように最初に数値かどうか判断するのも良いと思います！

```php
if (is_numeric($num)) {
    if ($num % 2 == 0) {
        var_dump($num . "は偶数です");
    } else {
        var_dump($num . "は奇数です");
    }
}
```

2021-12-22 00:33 UTC, kazu-taka commented on chap2_3.php
> +}
@terry-man-com 
こちらもフォーマッターの利用をお願いします✨
また、処理をグループ化して、グループの間に空行を1行入れることで、見やすくなります✨
2_1、2_2の課題も同様です😊
```php
var_dump("数学の点数を入力してください");
$score_1 = trim(fgets(STDIN));

var_dump("国語の点数を入力してください");
$score_2 = trim(fgets(STDIN));

if ($score_1 >= 80 && $score_2 >= 80) {
    var_dump("合格です。");
} elseif ($score_1 >= 50 && $score_2 >= 50) {
    var_dump("追試です。");
} else {
    var_dump("不合格です。");
} 
```

2021-12-22 01:50 UTC, terry-man-com commented
課題の修正を行いました。確認よろしくお願いします。
なお、chap2_2.phpの課題なんですが、小数を入力するとelseの処理が行われてしまうので、$numに入力された値が整数かをis_int()関数で判定した後にifから先の処理が行われるようにしたほうがいいのかと思い、Chap2_4.phpファイルにis_numericをis_intに変えてコードを書いてみましたがうまく処理されません。おそらく3行目の処理でターミナルから入力された値がも整数と見なされていないから、is_intで真と判定されずカッコ外の処理になっているのではと感じます。
<img width="538" alt="スクリーンショット 2021-12-22 10 34 02" src="https://user-images.githubusercontent.com/93232230/147021361-7df8bd5b-c2f1-46cf-aec1-b5981b4f6dfa.png">

2021-12-22 02:52 UTC, kzri4 commented
こちら確認しました！
`is_int()`関数で上手く行かない原因は、`fgets()`関数の返り値が文字列(string型)になることが原因ですね 試しに`var_dump($num);`を`$num = trim(fgets(STDIN));`のすぐ下に入れてみてください！ stringで返ってくると思います😊


https://www.php.net/manual/ja/function.fgets.php

公式によれば`is_int()`関数は整数型であれば、`true`になり、{}内の

```    
    if ($num % 2 == 0) {
        var_dump($num . "は偶数です");
    } else {
        var_dump($num . "は奇数です");
    }
```

に進みますが、整数型でないと判定されれば、{}内には進まないため、頂いた画像のように終了するという形です！

2021-12-22 03:04 UTC, kzri4 commented on chap2_3.php
> +} elseif ($score_1 >= 50 && $score_2 >= 50) {
追試の条件ですが、今のままでは課題文の以下の条件にならないので修正をお願いします😊

`条件 2 : 条件 1 に該当しない かつ 入力した点数のうち どちらかが50点以上 だったら、追試です。 と出力。`

今のままだと、 両方とも50点以上なら追試という形になってます！

2021-12-23 07:52 UTC, terry-man-com commented
2_3.phpを修正しました。確認お願いします！
2_４.phpの小数を入力しても”奇数です”となる問題についてですが、stringになっていたのを確認したので、fgets()関数の前にintval()関数を使って、標準入力したものをintに変換することでif()以下の処理はされました。しかし、まだ小数でも処理がされてしまいます。elseif($numが奇数の場合は以下の処理)というようにすればいいのでしょうか？

2021-12-23 07:54 UTC, terry-man-com commented
処理した時の画像を添付し忘れました。
![Uploading スクリーンショット 2021-12-23 16.49.16.png…]()

2021-12-23 08:04 UTC, terry-man-com commented
うまくできなかったのでもう一度貼ります。
<img width="459" alt="スクリーンショット 2021-12-23 16 49 16" src="https://user-images.githubusercontent.com/93232230/147208437-90058fda-92a1-4017-bd89-ea8eb2756aac.png">

2021-12-23 09:02 UTC, kzri4 commented
`2_3.php`はOKです!

<br>

 `2_４.php`の質問に関してすが､ そもそも`intval()関数`では､小数点は切り捨てされてしまうので､頂いた画像のように`3.5`と入力しても､小数点は省かれ､戻り値は整数型の`3`  という形になります｡
そのため､if()以下に進み､2で割り切れないため､"3は奇数です"という結果になっております｡😊


![スクリーンショット 2021-12-23 17 50 04](https://user-images.githubusercontent.com/68971142/147214702-1abe0e1c-4d55-45ca-98e7-e38629e8bf86.png)
https://www.flatflag.nir87.com/intval-721

![スクリーンショット 2021-12-23 18 01 32](https://user-images.githubusercontent.com/68971142/147215784-72be347f-7fa5-4f50-9377-a6ee088c035c.png)
https://www.php.net/manual/ja/language.types.integer.php#language.types.integer.casting

2021-12-23 13:07 UTC, merged