Chapter5課題
terry-man-com/furiPHP_exercise pull request #5
Opened 2022-01-15 06:31 UTC by terry-man-com

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/05.md

### 課題番号

課題５

### 現在の状況

constellation関数の作成
星座の判定、signs["name"]の取り出し方がわからない。

### 期待していた動作

### 調べたこと・参考にしたURL

2022-01-15 07:00 UTC, kazu-taka commented on chap5_1.php
> +    }
@terry-man-com 
`$signs`には星座の情報が全て入っています✨
foreach関数を使用して、`$signs`から1件ずつデータを取得して、`$sign`に代入して処理をしています。
if文のところも判定している値も、正しく取得できているので問題ないです！
if文の中でreturnしている内容ですが、`$sings`だと全体の配列を指定しまっているので、今判断している`$sing`の中のnameを指定すると、正しい値が取得できると思います✨

2022-01-15 07:32 UTC, terry-man-com commented on chap5_1.php
> +    }
ありがとうございます。
if文の中身についてなのですが、、、
フォームに入力された月と日から$start_m,$start_d,$end_m,$end_dを比較して真であることを判定した後、$signs["name"]の該当の番号の値を取得しなければならないと思うのですが、そこの書き方がわかりません。修正したものを一回プッシュします。

2022-01-15 07:44 UTC, kazu-taka commented on chap5_1.php
> +    }
@terry-man-com 
if文の中の`$sign`には今判定している星座の内容がセットされています！
ifの中を通っているということは、判定してtrueになっているので、その時の`$sing`の中からnameを指定するだけでOKです！！
一度ifの中で`var_dump($sign)`をして頂けると、`$sign`にどのような連想配列がセットされているかイメージが湧くかと思います✨
`$start_m`等に値をセットできているので、同じように考えていただければOKです！！

2022-01-15 11:19 UTC, terry-man-com commented on chap5_1.php
> +    }
ありがとうございます！理解しました。
if文の(~)中の条件が真の時だけ{~}の処理がされるので、(~)内の条件に当てはまらないものは処理がされず、終わる。そして、それが$signsの12番目まで繰り返されるという流れで合ってますか？？

修正版２も出しましたのでチェックお願いします！

2022-01-15 12:21 UTC, kazu-taka commented on chap5_1.php
> +    }
@terry-man-com 
if文で該当データが存在した場合、returnでconstellation関数から該当データ(星座の名前)を返して処理を終了します！
ですので、3月21日を日付を指定した場合は、配列の1件目が該当するので、1件目の星座の名前をreturnして処理が終了します✨

2022-01-15 12:27 UTC, kazu-taka requested changes
@terry-man-com 
コメントしたので修正お願いします🙏

2022-01-15 12:27 UTC, kazu-taka commented on chap5_1.php
> +        if (($month == $start_m || $month == $end_m) && ($day >= $start_d || $day <= $end_d)) {
@terry-man-com 
この判定条件だと、4月21日を指定した場合、`$month == $end_m`がtrue、`$day >= $start_d`もtrueとなり、牡羊座と判定されてしまいませんか！？^^;
判定する場合は、3/21〜4/19にの中に入っているか判定する必要があるので、修正お願いします🙏

【判定条件】
![image](https://user-images.githubusercontent.com/5278718/149621671-797e1063-f37f-4d1e-b33a-1c1cb5eb76cb.png)

2022-01-15 12:41 UTC, terry-man-com commented on chap5_1.php
> +        if (($month == $start_m || $month == $end_m) && ($day >= $start_d || $day <= $end_d)) {
すいません。こちらを修正したものをpushします！
奥さんにドヤ顔で誕生日入れさせて、違う星座出て恥ずかしかったです 😱

2022-01-15 13:03 UTC, terry-man-com commented on chap5_1.php
> +    }
ありがとうございます😃
処理の流れがわからなかったんですけど、理解できました！

2022-01-15 22:23 UTC, kazu-taka commented on chap5_1.php
> +        if (($month == $start_m || $month == $end_m) && ($day >= $start_d || $day <= $end_d)) {
@terry-man-com 
奥さんにテストしてもらうことができてよかったですね笑

2022-01-15 22:23 UTC, kazu-taka commented
@terry-man-com 
問題ないのでマージしてOKです👍
![LGTM](https://image.lgtmoon.dev/99033)

2022-01-16 01:21 UTC, terry-man-com commented
ありがとうございます。早速マージします！

2022-01-16 01:22 UTC, merged