Challenge課題１
terry-man-com/furiPHP_exercise pull request #6
Opened 2022-01-18 00:42 UTC by terry-man-com

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/06.md

### メッセージ

課題が終了しましたのでチェックよろしくお願いします！！

2022-01-18 01:05 UTC, kazu-taka requested changes
@terry-man-com 
コメントしたので確認お願いします😊

2022-01-18 01:05 UTC, kazu-taka commented on challenge1_1.php
> +echo "現在の時刻:" . date("H") . "時" . date("i") ."分". date("i") . "分" . "\n";
@terry-man-com 
php.iniファイルで `date.timezone = "Asia/Tokyo"`を指定しているので、こちらはでtimezoneを指定しなくても良いです✨
また、date関数の引数を変更するだけで、1つのdate関数だけで実現可能です！
https://syncer.jp/php-date-strtotime

(例)
![image](https://user-images.githubusercontent.com/5278718/149852782-1210780f-1b28-4355-8552-172ed49123ce.png)

2022-01-18 01:05 UTC, kazu-taka commented on challenge1_3.php
> +    echo $teams[0] . "\n" . $teams[1] . "\n" . $teams[2] . "\n";
@terry-man-com 
`$teams`の配列になっているので、同じようにforeachを使用した方が、配列の要素数が変わった場合でも、プログラムを変更しなくてもよくなります✨

2022-01-18 01:05 UTC, kazu-taka commented on challenge1_5.php
> +    $life = $hit_point - $attack;
@terry-man-com 
この方法だと、残りのLifeがマイナスで表示されたりしないですかね！？
マイナスになる場合は0で表示するように修正お願いします✨

2022-01-18 05:15 UTC, terry-man-com commented on challenge1_5.php
> +    $life = $hit_point - $attack;
チェックありがとうございます😊
マイナスになってしまいます。汗
本日泊まり勤務のため明日以降修正し、プッシュします！申し訳ありません。

2022-01-20 02:34 UTC, terry-man-com commented on challenge1_1.php
> +echo "現在の時刻:" . date("H") . "時" . date("i") ."分". date("i") . "分" . "\n";
なるほど！
date関数は日時に対応する英字を引数にして、あげれば、日時が習得可能をいうことですね！よくわかりました😃

2022-01-20 02:37 UTC, terry-man-com commented on challenge1_3.php
> +    echo $teams[0] . "\n" . $teams[1] . "\n" . $teams[2] . "\n";
すいません。回答の意味を理解できません。
つまりはこのように配列の中に配列がある場合は、foreachで要素を取り出した方が良いということでしょうか？？

2022-01-20 02:46 UTC, terry-man-com commented
修正が遅くなりました。チェックよろしくお願いします！

2022-01-20 02:52 UTC, kazu-taka commented on challenge1_3.php
> +    echo $teams[0] . "\n" . $teams[1] . "\n" . $teams[2] . "\n";
@terry-man-com 
以下の説明だとどうでしょうか✨
```php
foreach($all_teams as $teams) {
    // $teamsも配列になっているのでさらにforeachで取り出し可能(foreachの中にさらにforeachを書くイメージ)
}
```

2022-01-20 02:57 UTC, kazu-taka commented on challenge1_5.php
> +    $life = $hit_point - $attack;
@terry-man-com 
別のところを修正していただいたようですが、「HPが0になったらゲーム終了して、画面にHPを0と表示する」を満たせば良いので `$hit_point - $attack;`が0未満の時は0をセット、0以上の時はそのまま引いた値をセットというプログラムになります！

2022-01-20 03:02 UTC, kazu-taka commented on challenge1_5.php
> +    }
@terry-man-com 
先程コメントした `$life`を求める部分を修正した場合、if文を使用するのであれば、以下のような流れがシンプルになるかと思います✨
(変なところがあったら、すぐに言ってください笑)
switchを使用する場合は、書き方が変わります✨


```php
if (攻撃が1 or 2 or 3) {
    if (アタックが2000以上) {
        クリティカルヒットを表示
    }
    ダメージ表示

    if (ライフが0) {
        敵を倒したを表示
    }
} else {
    攻撃に失敗
}

2022-01-20 07:08 UTC, terry-man-com commented on challenge1_3.php
> +    echo $teams[0] . "\n" . $teams[1] . "\n" . $teams[2] . "\n";
理解できました！

2022-01-20 07:16 UTC, terry-man-com commented on challenge1_5.php
> +    }
遅くなりました。
修正はして、ダメージ０以下の時は０と表示させるようになりましたが、最初に1〜３の数字を入れないとループに入らないです。

2022-01-20 07:34 UTC, terry-man-com commented on challenge1_5.php
> +    }
ループに入らない理由は解決しました！修正２の方で間違っていた箇所を直しましたのでチェックよろしくお願いします！

2022-01-20 12:46 UTC, kazu-taka requested changes
@terry-man-com 
あと1歩です✨
コメントしたので修正お願いします😊

2022-01-20 12:46 UTC, kazu-taka commented on challenge1_5.php
> +    echo $num;
@terry-man-com 
ここでechoすると、1と入力した時に
```
1
1
```
と2つ表示されないですかね！？

2022-01-20 12:46 UTC, kazu-taka commented on challenge1_5.php
> +    }
@terry-man-com 
VSCodeのフォーマッターを使用してインデントやスペースの修正をお願いします✨

2022-01-20 13:07 UTC, terry-man-com commented on challenge1_5.php
> +    }
夜遅くありがとうございます！
修正しましたのでチェックお願いします！

2022-01-20 21:29 UTC, kazu-taka commented
問題ないのでマージしてOKです😊
https://lgtmoon.herokuapp.com/

2022-01-21 03:32 UTC, terry-man-com commented
了解しました！
ヒント（ほぼ答えでしたが）のおかげで無事にできました。ありがとうございました😃

2022-01-21 03:33 UTC, merged